# Generated by Django 4.2.17 on 2025-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uniq_code',
            field=models.CharField(default=1234, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
